spring:
  redis:
      host: 192.168.3.60
      port: 6379
#      password: youngo_online_edu
  passportDs:
      url: jdbc:mysql://192.168.3.60:3306/db_passport?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 123456
      driverClassName : com.mysql.jdbc.Driver
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
#      validation-query: SELECT 1

  datasource:
      url: jdbc:mysql://192.168.3.60:3306/db_house?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driverClassName : com.mysql.jdbc.Driver
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
logging:
  level:
    com:
      youngo:
        erp:
          dao:  DEBUG



